name=TKJHAT
version=0.1.0
author=Petrus Raisanen, Otto Syri, Ahti Syri, Ivan Sanchez Milara
maintainer=Petrus Raisanen <Petrus.Raisanen@student.oulu.fi>
sentence=Arduino library for the Pico HAT extension board for the Raspberry Pi Pico.
paragraph=Port of the original TKJHAT Pico C SDK to Arduino
category=Device Control
architectures=rp2040
url=https://github.com/PetrusRaisanen/TKJHAT-Arduino
license=MIT
includes=TKJHAT.h