name=TKJHAT
version=0.1.0
author=Your Name
maintainer=Your Name
sentence=Arduino library for the Pico HAT extension board for the Raspberry Pi Pico.
paragraph=Port of the original TKJHAT Pico C SDK to Arduino
category=Device Control
architectures=rp2040